export const Urls = {
  ABOUT: "/about",
  HOME: "/",
  BLOGS: "/blogs",
  CONTACT: "/contact",
  SERVICES: "/services",
  PASSWORDRESET: "/auth/password-reset",
  PASSWORDRESETTOKEN: "/auth/password-reset/token",
  PASSWORDRESETFORM: "/auth/password-reset/form",
  PASSWORDRESETSUCCESS: "auth/password-reset/success",
  LOGIN: "/auth/login",
  SIGNUP: "/auth/sign-up",
  PLAYERSIGNUP: "/auth/player/sign-up",
  SCOUTSIGNUP: "/auth/scout/sign-up",
  COACHSIGNUP: "/auth/coach/sign-up",
  PLAYER_SPOTLIGHT: "/dashboard/player/spotlight",
  PLAYER_SETTINGS: "/dashboard/player/settings",
  PLAYER_GALLERY: "/dashboard/player/gallery",
  PLAYER_PROFILE: "/dashboard/player/profile",
  SCOUT_OVERVIEW: "/dashboard/scout/overview",
};

export const positions = [
  "Goalkeeper",
  "Center Back",
  "Right Back",
  "Left Back",
  "Sweeper",
  "Defensive Midfielder",
  "Central Midfielder",
  "Attacking Midfielder",
  "Right Midfielder",
  "Left Midfielder",
  "Right Wing Forward",
  "Left Wing Forward",
  "Striker",
  "Center Forward",
  "False Nine",
  "Center Midfielder",
  "Deep-Lying Playmaker",
  "Box-to-Box Midfielder",
  "Advanced Playmaker",
  "Trequartista",
  "Second Striker",
  "Target Man",
  "Poacher",
  "Wide Midfielder",
  "Inside Forward",
  "Right Wing-Back",
  "Left Wing-Back",
  "Libero",
  "Wingback",
  "Holding Midfielder",
  "Full-Back",
  "Center Half",
  "Stopper",
  "Shadow Striker",
];
